/**
 * Centralized configuration for Yuva Shakti Sangam.
 */
export const eventConfig = {
  name: "Yuva Shakti Sangam",
  taglineHindi: "युवा शक्ति • राष्ट्र शक्ति",
  taglineEnglish: "Where the energy of youth meets the responsibility of nation-building.",
  subtext: "An open, high-energy gathering of thinkers, builders, and changemakers shaping the future of Bharat.",
  date: "2026-09-06",
  dateDisplay: "06 September 2026",
  dayDisplay: "Sunday",
  timeDisplay: "4:00 PM – 8:00 PM IST",
  startTime: "16:00",
  endTime: "20:00",
  timezone: "Asia/Kolkata",
  targetIsoDate: "2026-09-06T16:00:00+05:30",
  endIsoDate: "2026-09-06T20:00:00+05:30",
  venueName: "Shree Saurashtra Patel Samaj",
  venueAddress: "Isanpur Rd, Chandranagar Society, Basant Nagar, Maninagar, Ahmedabad",
  location: "Shree Saurashtra Patel Samaj, Isanpur Rd, Chandranagar Society, Basant Nagar, Maninagar, Ahmedabad",
  locationShort: "Shree Saurashtra Patel Samaj, Maninagar, Ahmedabad",
  venueNote: "Shree Saurashtra Patel Samaj, Isanpur Rd, Chandranagar Society, Basant Nagar, Maninagar, Ahmedabad",
  googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Shree+Saurashtra+Patel+Samaj+Maninagar,+Isanpur+Rd,+Chandranagar+Society,+Basant+Nagar,+Maninagar,+Ahmedabad",
  registrationUrl: "/register",
  registrationFee: "₹50",
  registrationFeeAmount: 50,
  inclusions: [
    "Official Delegate ID Card",
    "High Tea & Refreshments",
    "Official E-Certificate of Participation",
    "Full Zone & Sports Access",
    "Open Samvaad Participation",
  ],
  host: "Rashtriya Swayamsevak Sangh (RSS)",
  siteUrl: "https://yuvashaktisangam.org",
  email: "yuvashaktisangam2047@gmail.com",
  instagramUrl: "https://www.instagram.com/yuvashaktisangam?igsi=NHhvdmIxNmo1bWVy",
  instagramHandle: "@yuvashaktisangam",
  logoUrl: "/images/logo.png",
  upi: {
    id: "7046232003@upi",
    name: "KUSHAL GHANSHYAMBHAI",
    amount: 50,
    currency: "INR",
    note: "Yuva Shakti Sangam Entry Pass",
    qrImageUrl: "/images/payment-qr.png",
    getUpiUrl: () =>
      "upi://pay?pa=7046232003@upi&pn=KUSHAL%20GHANSHYAMBHAI&am=50&cu=INR&tn=Yuva%20Shakti%20Sangam%20Pass",
  },
  coordinators: [
    {
      name: "Dhruvil Bhatt",
      phone: "+91 90547 37915",
      phoneRaw: "+919054737915",
      whatsappUrl: "https://wa.me/919054737915?text=Namaste%20Dhruvil%20bhai%2C%20I%20have%20a%20query%20regarding%20Yuva%20Shakti%20Sangam.",
    },
    {
      name: "Kushal Patel",
      phone: "+91 70462 32003",
      phoneRaw: "+917046232003",
      whatsappUrl: "https://wa.me/917046232003?text=Namaste%20Kushal%20bhai%2C%20I%20have%20a%20query%20regarding%20Yuva%20Shakti%20Sangam.",
    },
  ],
};

